services:
  # 前端服務
  - type: web
    name: restarter-frontend
    env: static
    buildCommand: cd restarter-voice-mvp/frontend && npm install && npm run build
    staticPublishPath: ./restarter-voice-mvp/frontend/dist
    routes:
      - type: rewrite
        source: /api/*
        destination: /index.html
      - type: rewrite
        source: /*
        destination: /index.html

  # 後端 API 服務
  - type: web
    name: restarter-backend
    env: node
    plan: free
    buildCommand: cd restarter-voice-mvp/backend && npm install
    startCommand: cd restarter-voice-mvp/backend && PORT=$PORT node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: OPENAI_API_KEY
        value: "your-openai-api-key"
      - key: AZURE_KEY
        value: "your-azure-key"
      - key: AZURE_REGION
        value: "your-azure-region" 