#!/bin/bash

echo "🧪 JobFinder中文技能功能測試"
echo "============================"
echo "📱 本機IP: $(ifconfig | grep "inet " | grep -v 127.0.0.1 | awk '{print $2}' | head -1)"
echo ""

# 測試頁面訪問
echo "🔍 測試頁面訪問..."

# 測試JobFinder頁面
if curl -s http://localhost:5173/job-finder > /dev/null; then
    echo "✅ JobFinder頁面 - 可訪問"
else
    echo "❌ JobFinder頁面 - 無法訪問"
fi

echo ""
echo "🎯 測試總結:"
echo "📱 手機版訪問地址:"
echo "   - JobFinder: http://172.20.10.6:5173/job-finder"
echo ""
echo "💻 電腦版訪問地址:"
echo "   - JobFinder: http://localhost:5173/job-finder"
echo ""
echo "✨ JobFinder中文技能功能測試步驟:"
echo ""
echo "1. 語言一致性檢查:"
echo "   ✅ 所有欄位現在都是中文："
echo "   - 搜尋職位：職位名稱、公司名稱..."
echo "   - 工作地點：台北市、新北市、桃園市..."
echo "   - 工作類型：全職、兼職、實習、遠端"
echo "   - 技能要求：選擇技能... ← 現在也是中文"
echo ""
echo "2. 中文技能分類測試:"
echo "   技能下拉選單現在包含以下中文分類："
echo ""
echo "   🔧 技術類技能 (20+項):"
echo "     - 前端：React, TypeScript, JavaScript, HTML/CSS, Git"
echo "     - 後端：Node.js, Python, SQL, MongoDB, AWS"
echo "     - 設計：Figma, Adobe創意套件, UI/UX設計, 原型設計"
echo "     - 數據：數據分析, 機器學習, Tableau"
echo "     - 其他：Docker, 微服務, 雲端運算, 行動開發等"
echo ""
echo "   👔 管理與領導技能 (12項):"
echo "     - 專案管理, 領導力, 溝通技巧, 敏捷開發"
echo "     - 團隊管理, 策略規劃, 風險管理"
echo "     - 預算管理, 利害關係人管理, 變革管理等"
echo ""
echo "   📈 行銷與業務技能 (15項):"
echo "     - 數位行銷, SEO優化, 社群媒體行銷"
echo "     - 銷售, 客戶服務, 業務開發"
echo "     - 品牌管理, 活動規劃, 公關"
echo "     - Google Analytics, Facebook廣告, Google廣告等"
echo ""
echo "   💰 財務與會計技能 (12項):"
echo "     - 財務分析, 會計, 簿記, 稅務申報"
echo "     - 預算規劃, 財務建模, 審計, 成本控制"
echo "     - QuickBooks, Excel, SAP, Oracle財務系統等"
echo ""
echo "   👥 人力資源技能 (11項):"
echo "     - 招募, 人才招募, 員工關係"
echo "     - 績效評估, 培訓發展, 薪酬福利"
echo "     - 人資政策, 勞動法規, 職場安全等"
echo ""
echo "   🎨 設計與創意技能 (12項):"
echo "     - 平面設計, 網頁設計, 標誌設計"
echo "     - 插畫, 攝影, 影片剪輯"
echo "     - 3D建模, 動畫, Adobe創意套件等"
echo ""
echo "   🏥 醫療與健康技能 (12項):"
echo "     - 病人照護, 醫學術語, 臨床技能"
echo "     - 護理, 藥學, 醫療帳單"
echo "     - 醫療管理, 病歷管理, CPR等"
echo ""
echo "   📚 教育與培訓技能 (12項):"
echo "     - 教學, 課程開發, 學生評估"
echo "     - 班級管理, 線上教學, 教育科技"
echo "     - 特殊教育, 英語教學, 成人教育等"
echo ""
echo "   ⚖️ 法律與行政技能 (12項):"
echo "     - 法律研究, 合約審查, 法律寫作"
echo "     - 行政支援, 辦公室管理, 文件管理"
echo "     - 行程管理, 差旅安排, 會議協調等"
echo ""
echo "   🔧 製造與工程技能 (12項):"
echo "     - CAD設計, 品質控制, 製造流程"
echo "     - 機械工程, 電機工程, 土木工程"
echo "     - 產品開發, 六標準差, 精實製造等"
echo ""
echo "   🛍️ 零售與服務技能 (12項):"
echo "     - 零售銷售, 庫存管理, 客戶服務"
echo "     - 現金處理, POS系統, 商品陳列"
echo "     - 店面管理, 防損, 餐飲服務等"
echo ""
echo "   🌍 語言與翻譯技能 (15項):"
echo "     - 英語, 中文, 日語, 韓語, 西班牙語"
echo "     - 法語, 德語, 義大利語, 葡萄牙語"
echo "     - 翻譯, 口譯, 校對, 文案撰寫等"
echo ""
echo "   📋 其他專業技能 (12項):"
echo "     - 研究, 資料輸入, Microsoft Office"
echo "     - 虛擬助理, 活動規劃, 物流"
echo "     - 品質保證, 測試, 文件撰寫等"
echo ""
echo "3. 中文技能篩選測試:"
echo "   - 選擇「教學」技能 → 應該顯示英文教師職位"
echo "   - 選擇「護理」技能 → 應該顯示護理師職位"
echo "   - 選擇「數位行銷」技能 → 應該顯示數位行銷專員職位"
echo "   - 選擇「會計」技能 → 應該顯示會計專員職位"
echo "   - 選擇「專案管理」技能 → 應該顯示專案經理職位"
echo "   - 選擇「UI/UX設計」技能 → 應該顯示UI/UX設計師職位"
echo ""
echo "4. 多技能組合測試:"
echo "   - 同時選擇「教學」和「英語」→ 應該顯示英文教師"
echo "   - 同時選擇「數位行銷」和「SEO優化」→ 應該顯示數位行銷專員"
echo "   - 同時選擇「專案管理」和「領導力」→ 應該顯示專案經理"
echo ""
echo "5. 職位技能標籤檢查:"
echo "   職位卡片中的技能標籤現在都是中文："
echo "   - 前端開發工程師：React, TypeScript, JavaScript, HTML/CSS, Git"
echo "   - 數位行銷專員：數位行銷, 社群媒體行銷, SEO優化, 內容創作"
echo "   - 會計專員：會計, 簿記, 稅務申報, Excel, QuickBooks"
echo "   - 護理師：護理, 病人照護, 臨床技能, 病歷管理, CPR"
echo ""
echo "📱 手機版測試:"
echo "1. 確保手機和電腦在同一WiFi網絡"
echo "2. 在手機瀏覽器中訪問: http://172.20.10.6:5173/job-finder"
echo "3. 測試中文技能下拉選單的顯示"
echo "4. 測試中文技能篩選功能"
echo "5. 測試響應式設計"
echo ""
echo "🎉 更新內容："
echo "✅ 技能列表全部改為中文"
echo "✅ 職位技能標籤全部改為中文"
echo "✅ 保持技術術語的國際通用性（如React, Python等）"
echo "✅ 語言一致性：所有欄位都是中文"
echo "✅ 適合中文用戶使用"
echo "✅ 技能篩選功能完全中文化"
echo ""
echo "🎉 測試完成！"
