#!/bin/bash

echo "🧪 JobFinder技能篩選功能測試"
echo "============================"
echo "📱 本機IP: $(ifconfig | grep "inet " | grep -v 127.0.0.1 | awk '{print $2}' | head -1)"
echo ""

# 測試頁面訪問
echo "🔍 測試頁面訪問..."

# 測試JobFinder頁面
if curl -s http://localhost:5173/job-finder > /dev/null; then
    echo "✅ JobFinder頁面 - 可訪問"
else
    echo "❌ JobFinder頁面 - 無法訪問"
fi

echo ""
echo "🎯 測試總結:"
echo "📱 手機版訪問地址:"
echo "   - JobFinder: http://172.20.10.6:5173/job-finder"
echo ""
echo "💻 電腦版訪問地址:"
echo "   - JobFinder: http://localhost:5173/job-finder"
echo ""
echo "✨ JobFinder技能篩選功能測試步驟:"
echo ""
echo "1. 頁面佈局檢查:"
echo "   - 左上角有「← 返回個人資料」按鈕"
echo "   - 左側篩選條件區域包含："
echo "     * 搜尋職位輸入框"
echo "     * 工作地點下拉選單"
echo "     * 工作類型下拉選單"
echo "     * 技能要求下拉選單 ← 新增功能"
echo "     * 清除所有篩選按鈕"
echo "   - 右側顯示推薦職位列表"
echo ""
echo "2. 技能要求下拉選單測試:"
echo "   - 點擊「技能要求」下拉選單"
echo "   - 應該顯示「選擇技能...」作為預設選項"
echo "   - 下拉選單包含50+種技能選項："
echo "     * 前端技能：React, TypeScript, JavaScript, HTML/CSS, Vue.js, Angular"
echo "     * 後端技能：Node.js, Python, SQL, MongoDB, PHP, Java, C#"
echo "     * 設計技能：Figma, Adobe Creative Suite, UI/UX Design"
echo "     * 數據技能：Data Analysis, Machine Learning, Tableau"
echo "     * 管理技能：Project Management, Leadership, Communication"
echo "     * 其他技能：Docker, AWS, Mobile Development, Blockchain等"
echo ""
echo "3. 技能選擇功能測試:"
echo "   - 從下拉選單選擇一個技能（例如：React）"
echo "   - 選擇的技能應該出現在下方的紫色標籤中"
echo "   - 可以選擇多個技能"
echo "   - 點擊技能標籤上的「×」可以移除該技能"
echo "   - 重複選擇相同技能不會重複添加"
echo ""
echo "4. 篩選功能測試:"
echo "   - 選擇技能後，職位列表應該根據技能進行篩選"
echo "   - 只顯示包含所選技能的職位"
echo "   - 職位卡片中的技能標籤會高亮顯示匹配的技能"
echo "   - 匹配度百分比會根據技能匹配情況計算"
echo ""
echo "5. 用戶技能提示測試:"
echo "   - 如果用戶已登入且有技能資料，會顯示「您的技能：...」"
echo "   - 顯示用戶在個人資料中設定的技能"
echo "   - 未登入用戶不會顯示此提示"
echo ""
echo "6. 清除篩選功能測試:"
echo "   - 點擊「清除所有篩選」按鈕"
echo "   - 所有篩選條件應該被重置"
echo "   - 技能標籤應該全部消失"
echo "   - 職位列表應該顯示所有職位"
echo ""
echo "7. 響應式設計測試:"
echo "   - 在手機上測試下拉選單是否正常顯示"
echo "   - 技能標籤在小螢幕上是否正確換行"
echo "   - 整體佈局是否適應不同螢幕尺寸"
echo ""
echo "📱 手機版測試:"
echo "1. 確保手機和電腦在同一WiFi網絡"
echo "2. 在手機瀏覽器中訪問: http://172.20.10.6:5173/job-finder"
echo "3. 測試技能下拉選單功能"
echo "4. 測試技能選擇和篩選功能"
echo "5. 測試響應式設計"
echo ""
echo "🎉 新增功能："
echo "✅ 技能要求下拉選單"
echo "✅ 50+種技能選項"
echo "✅ 多選技能功能"
echo "✅ 技能標籤顯示"
echo "✅ 技能篩選功能"
echo "✅ 用戶技能提示"
echo ""
echo "🎉 測試完成！"
